version: '3.1'
services:
  backend:
    build: backend
    image: backend/rating-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=${ACTIVE_BACKEND_PROFILE}
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
  frontend:
    build: ./frontend
    volumes:
       - ./frontend/src:/home/frontend/src
       - ./frontend/public:/home/frontend/public
    ports:
      - "9000:9000"